# Generated by Django 5.2.9 on 2025-12-10 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, verbose_name='Тикер')),
                ('class_code', models.CharField(max_length=10, verbose_name='Секция торгов')),
                ('nano', models.IntegerField(verbose_name='Дробная часть цены')),
                ('units', models.IntegerField(verbose_name='Целая часть цены')),
                ('logo_url', models.URLField(verbose_name='URL логотипа')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='CheckAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, verbose_name='Тикер')),
                ('buy_price', models.FloatField(verbose_name='Цена покупки')),
                ('buy_count', models.IntegerField(verbose_name='Количество')),
                ('buy_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата покупки')),
                ('current_price', models.FloatField(verbose_name='Текущая цена')),
                ('excepted_price', models.FloatField(verbose_name='Ожидаемая цена')),
            ],
            options={
                'verbose_name': 'Контролируемая акция',
                'verbose_name_plural': 'Контролируемые акции',
                'ordering': ['buy_date'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_capital', models.IntegerField(verbose_name='Доступный капитал (руб.)')),
                ('broker_commission', models.FloatField(verbose_name='Комиссия брокера (%)')),
                ('dividend_tax', models.FloatField(verbose_name='Налог на дивиденды (%)')),
                ('central_bank_rate', models.FloatField(verbose_name='Ключевая ставка (%)')),
                ('dividends_from_date', models.DateField(verbose_name='Дата старта отсечки дивидендов')),
                ('dividends_to_date', models.DateField(verbose_name='Дата конца отсечки дивидендов')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
