# Generated by Django 5.2.9 on 2025-12-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, verbose_name='Тикер')),
                ('company_name', models.CharField(max_length=255, verbose_name='Компания')),
                ('payday', models.DateField(verbose_name='Дата отсечки')),
                ('dividend', models.FloatField(verbose_name='Дивиденд (руб.)')),
                ('profitability', models.FloatField(verbose_name='Доходность (%)')),
                ('price', models.FloatField(verbose_name='Цена (руб.)')),
                ('priority', models.IntegerField(verbose_name='Приоритет')),
                ('max_part', models.IntegerField(verbose_name='Максимальная доля (%)')),
            ],
            options={
                'verbose_name': 'Дивиденд',
                'verbose_name_plural': 'Дивиденды',
            },
        ),
    ]
