# Generated by Django 5.2.9 on 2025-12-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_assetdividend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetdividend',
            options={'ordering': ['-profitability'], 'verbose_name': 'Дивиденд', 'verbose_name_plural': 'Дивиденды'},
        ),
        migrations.AlterField(
            model_name='assetdividend',
            name='max_part',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальная доля (%)'),
        ),
        migrations.AlterField(
            model_name='assetdividend',
            name='priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='Приоритет'),
        ),
    ]
