# Generated by Django 5.2.9 on 2025-12-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_alter_assetdividend_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCandidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, verbose_name='Тикер')),
                ('price', models.FloatField(verbose_name='Цена (руб.)')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('costs', models.FloatField(verbose_name='Затраты (руб.)')),
                ('share', models.FloatField(verbose_name='Доля (%)')),
                ('dividend', models.FloatField(verbose_name='Дивиденд (руб.)')),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
            },
        ),
    ]
