# Generated by Django 5.2.9 on 2025-12-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0004_assetcandidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='tg_id',
            field=models.IntegerField(default=0, verbose_name='ID пользователя ТГ для отправки сообщения'),
            preserve_default=False,
        ),
    ]
