# Generated by Django 5.2.9 on 2025-12-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0005_settings_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkassets',
            name='is_notified',
            field=models.BooleanField(default=False, verbose_name='Проинформирована'),
        ),
    ]
